project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"

website:
  google-analytics: G-KWHRVQXNLK
  title: "Lucia Macakova"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Portfolio
        href: portfolio.qmd
      
    right:
      - icon: github
        href: https://github.com/lmacakova
      

  page-footer:
    left: "© 2025 Lucia Macakova"

format:
  html:
    theme: superhero
    toc: false
    code-copy: true
    css: styles_fixed.css

