<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Import of Datasets – Lucia Macakova</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1d4f84655f446305ac42a8f1abcf7405.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Lucia Macakova</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Import of Datasets</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="house-price-prediction" class="level1">
<h1>House Price Prediction</h1>
<p>The Ames Housing Dataset contains information on residential property sales in Ames, Iowa, USA, covering the period from 2006 to 2010. The dataset is publicly available through Kaggle at:</p>
<p>https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview</p>
<p>The data consists of three files: train.csv, test.csv, and data_description.txt. The train.csv file includes the target variable SalePrice, while the test.csv file contains the same feature set without the target variable. The data_description.txt file provides detailed explanations of all variables and is included at the end of this notebook to help readers understand the dataset.</p>
<p>Train_ds:</p>
<div id="99dadd13" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MSSubClass</th>
<th data-quarto-table-cell-role="th">MSZoning</th>
<th data-quarto-table-cell-role="th">LotFrontage</th>
<th data-quarto-table-cell-role="th">LotArea</th>
<th data-quarto-table-cell-role="th">Street</th>
<th data-quarto-table-cell-role="th">Alley</th>
<th data-quarto-table-cell-role="th">LotShape</th>
<th data-quarto-table-cell-role="th">LandContour</th>
<th data-quarto-table-cell-role="th">Utilities</th>
<th data-quarto-table-cell-role="th">LotConfig</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">PoolArea</th>
<th data-quarto-table-cell-role="th">PoolQC</th>
<th data-quarto-table-cell-role="th">Fence</th>
<th data-quarto-table-cell-role="th">MiscFeature</th>
<th data-quarto-table-cell-role="th">MiscVal</th>
<th data-quarto-table-cell-role="th">MoSold</th>
<th data-quarto-table-cell-role="th">YrSold</th>
<th data-quarto-table-cell-role="th">SaleType</th>
<th data-quarto-table-cell-role="th">SaleCondition</th>
<th data-quarto-table-cell-role="th">SalePrice</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Id</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>60</td>
<td>RL</td>
<td>65.0</td>
<td>8450</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>2</td>
<td>2008</td>
<td>WD</td>
<td>Normal</td>
<td>208500</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2</th>
<td>20</td>
<td>RL</td>
<td>80.0</td>
<td>9600</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>FR2</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>5</td>
<td>2007</td>
<td>WD</td>
<td>Normal</td>
<td>181500</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3</th>
<td>60</td>
<td>RL</td>
<td>68.0</td>
<td>11250</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>9</td>
<td>2008</td>
<td>WD</td>
<td>Normal</td>
<td>223500</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>70</td>
<td>RL</td>
<td>60.0</td>
<td>9550</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Corner</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>2</td>
<td>2006</td>
<td>WD</td>
<td>Abnorml</td>
<td>140000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5</th>
<td>60</td>
<td>RL</td>
<td>84.0</td>
<td>14260</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>FR2</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>12</td>
<td>2008</td>
<td>WD</td>
<td>Normal</td>
<td>250000</td>
</tr>
</tbody>
</table>

<p>5 rows × 80 columns</p>
</div>
</div>
</div>
<p>Test_ds:</p>
<div id="2baf000a" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MSSubClass</th>
<th data-quarto-table-cell-role="th">MSZoning</th>
<th data-quarto-table-cell-role="th">LotFrontage</th>
<th data-quarto-table-cell-role="th">LotArea</th>
<th data-quarto-table-cell-role="th">Street</th>
<th data-quarto-table-cell-role="th">Alley</th>
<th data-quarto-table-cell-role="th">LotShape</th>
<th data-quarto-table-cell-role="th">LandContour</th>
<th data-quarto-table-cell-role="th">Utilities</th>
<th data-quarto-table-cell-role="th">LotConfig</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">PoolArea</th>
<th data-quarto-table-cell-role="th">PoolQC</th>
<th data-quarto-table-cell-role="th">Fence</th>
<th data-quarto-table-cell-role="th">MiscFeature</th>
<th data-quarto-table-cell-role="th">MiscVal</th>
<th data-quarto-table-cell-role="th">MoSold</th>
<th data-quarto-table-cell-role="th">YrSold</th>
<th data-quarto-table-cell-role="th">SaleType</th>
<th data-quarto-table-cell-role="th">SaleCondition</th>
<th data-quarto-table-cell-role="th">SalePrice</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Id</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1461</th>
<td>20</td>
<td>RH</td>
<td>80.0</td>
<td>11622</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>MnPrv</td>
<td>NaN</td>
<td>0</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>113431.348154</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1462</th>
<td>20</td>
<td>RL</td>
<td>81.0</td>
<td>14267</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Corner</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>Gar2</td>
<td>12500</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>156069.039245</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1463</th>
<td>60</td>
<td>RL</td>
<td>74.0</td>
<td>13830</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>MnPrv</td>
<td>NaN</td>
<td>0</td>
<td>3</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>180724.011907</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1464</th>
<td>60</td>
<td>RL</td>
<td>78.0</td>
<td>9978</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>195835.483736</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1465</th>
<td>120</td>
<td>RL</td>
<td>43.0</td>
<td>5005</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>HLS</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>1</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>198040.287389</td>
</tr>
</tbody>
</table>

<p>5 rows × 80 columns</p>
</div>
</div>
</div>
<section id="information-about-datasets" class="level2">
<h2 class="anchored" data-anchor-id="information-about-datasets">Information about Datasets</h2>
<p>Train_ds:</p>
<div id="aaf58eea" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          91 non-null     object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuilt      1460 non-null   int64  
 19  YearRemodAdd   1460 non-null   int64  
 20  RoofStyle      1460 non-null   object 
 21  RoofMatl       1460 non-null   object 
 22  Exterior1st    1460 non-null   object 
 23  Exterior2nd    1460 non-null   object 
 24  MasVnrType     1452 non-null   object 
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object 
 27  ExterCond      1460 non-null   object 
 28  Foundation     1460 non-null   object 
 29  BsmtQual       1423 non-null   object 
 30  BsmtCond       1423 non-null   object 
 31  BsmtExposure   1422 non-null   object 
 32  BsmtFinType1   1423 non-null   object 
 33  BsmtFinSF1     1460 non-null   int64  
 34  BsmtFinType2   1422 non-null   object 
 35  BsmtFinSF2     1460 non-null   int64  
 36  BsmtUnfSF      1460 non-null   int64  
 37  TotalBsmtSF    1460 non-null   int64  
 38  Heating        1460 non-null   object 
 39  HeatingQC      1460 non-null   object 
 40  CentralAir     1460 non-null   object 
 41  Electrical     1459 non-null   object 
 42  1stFlrSF       1460 non-null   int64  
 43  2ndFlrSF       1460 non-null   int64  
 44  LowQualFinSF   1460 non-null   int64  
 45  GrLivArea      1460 non-null   int64  
 46  BsmtFullBath   1460 non-null   int64  
 47  BsmtHalfBath   1460 non-null   int64  
 48  FullBath       1460 non-null   int64  
 49  HalfBath       1460 non-null   int64  
 50  BedroomAbvGr   1460 non-null   int64  
 51  KitchenAbvGr   1460 non-null   int64  
 52  KitchenQual    1460 non-null   object 
 53  TotRmsAbvGrd   1460 non-null   int64  
 54  Functional     1460 non-null   object 
 55  Fireplaces     1460 non-null   int64  
 56  FireplaceQu    770 non-null    object 
 57  GarageType     1379 non-null   object 
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object 
 60  GarageCars     1460 non-null   int64  
 61  GarageArea     1460 non-null   int64  
 62  GarageQual     1379 non-null   object 
 63  GarageCond     1379 non-null   object 
 64  PavedDrive     1460 non-null   object 
 65  WoodDeckSF     1460 non-null   int64  
 66  OpenPorchSF    1460 non-null   int64  
 67  EnclosedPorch  1460 non-null   int64  
 68  3SsnPorch      1460 non-null   int64  
 69  ScreenPorch    1460 non-null   int64  
 70  PoolArea       1460 non-null   int64  
 71  PoolQC         7 non-null      object 
 72  Fence          281 non-null    object 
 73  MiscFeature    54 non-null     object 
 74  MiscVal        1460 non-null   int64  
 75  MoSold         1460 non-null   int64  
 76  YrSold         1460 non-null   int64  
 77  SaleType       1460 non-null   object 
 78  SaleCondition  1460 non-null   object 
 79  SalePrice      1460 non-null   int64  
dtypes: float64(3), int64(34), object(43)
memory usage: 923.9+ KB</code></pre>
</div>
</div>
<p>Test_ds:</p>
<div id="9a4889b3" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1459 non-null   int64  
 1   MSZoning       1455 non-null   object 
 2   LotFrontage    1232 non-null   float64
 3   LotArea        1459 non-null   int64  
 4   Street         1459 non-null   object 
 5   Alley          107 non-null    object 
 6   LotShape       1459 non-null   object 
 7   LandContour    1459 non-null   object 
 8   Utilities      1457 non-null   object 
 9   LotConfig      1459 non-null   object 
 10  LandSlope      1459 non-null   object 
 11  Neighborhood   1459 non-null   object 
 12  Condition1     1459 non-null   object 
 13  Condition2     1459 non-null   object 
 14  BldgType       1459 non-null   object 
 15  HouseStyle     1459 non-null   object 
 16  OverallQual    1459 non-null   int64  
 17  OverallCond    1459 non-null   int64  
 18  YearBuilt      1459 non-null   int64  
 19  YearRemodAdd   1459 non-null   int64  
 20  RoofStyle      1459 non-null   object 
 21  RoofMatl       1459 non-null   object 
 22  Exterior1st    1458 non-null   object 
 23  Exterior2nd    1458 non-null   object 
 24  MasVnrType     1443 non-null   object 
 25  MasVnrArea     1444 non-null   float64
 26  ExterQual      1459 non-null   object 
 27  ExterCond      1459 non-null   object 
 28  Foundation     1459 non-null   object 
 29  BsmtQual       1415 non-null   object 
 30  BsmtCond       1414 non-null   object 
 31  BsmtExposure   1415 non-null   object 
 32  BsmtFinType1   1417 non-null   object 
 33  BsmtFinSF1     1458 non-null   float64
 34  BsmtFinType2   1417 non-null   object 
 35  BsmtFinSF2     1458 non-null   float64
 36  BsmtUnfSF      1458 non-null   float64
 37  TotalBsmtSF    1458 non-null   float64
 38  Heating        1459 non-null   object 
 39  HeatingQC      1459 non-null   object 
 40  CentralAir     1459 non-null   object 
 41  Electrical     1459 non-null   object 
 42  1stFlrSF       1459 non-null   int64  
 43  2ndFlrSF       1459 non-null   int64  
 44  LowQualFinSF   1459 non-null   int64  
 45  GrLivArea      1459 non-null   int64  
 46  BsmtFullBath   1457 non-null   float64
 47  BsmtHalfBath   1457 non-null   float64
 48  FullBath       1459 non-null   int64  
 49  HalfBath       1459 non-null   int64  
 50  BedroomAbvGr   1459 non-null   int64  
 51  KitchenAbvGr   1459 non-null   int64  
 52  KitchenQual    1458 non-null   object 
 53  TotRmsAbvGrd   1459 non-null   int64  
 54  Functional     1457 non-null   object 
 55  Fireplaces     1459 non-null   int64  
 56  FireplaceQu    729 non-null    object 
 57  GarageType     1383 non-null   object 
 58  GarageYrBlt    1381 non-null   float64
 59  GarageFinish   1381 non-null   object 
 60  GarageCars     1458 non-null   float64
 61  GarageArea     1458 non-null   float64
 62  GarageQual     1381 non-null   object 
 63  GarageCond     1381 non-null   object 
 64  PavedDrive     1459 non-null   object 
 65  WoodDeckSF     1459 non-null   int64  
 66  OpenPorchSF    1459 non-null   int64  
 67  EnclosedPorch  1459 non-null   int64  
 68  3SsnPorch      1459 non-null   int64  
 69  ScreenPorch    1459 non-null   int64  
 70  PoolArea       1459 non-null   int64  
 71  PoolQC         3 non-null      object 
 72  Fence          290 non-null    object 
 73  MiscFeature    51 non-null     object 
 74  MiscVal        1459 non-null   int64  
 75  MoSold         1459 non-null   int64  
 76  YrSold         1459 non-null   int64  
 77  SaleType       1458 non-null   object 
 78  SaleCondition  1459 non-null   object 
 79  SalePrice      1459 non-null   float64
dtypes: float64(12), int64(25), object(43)
memory usage: 923.3+ KB</code></pre>
</div>
</div>
<p>Train_ds contains 1460 rows (instances) and 80 columns (variables), including the target row ‘SalePrice’, while test_ds contains 1459 rows (instances) and 79 columns (not the target column ‘SalePrice’). Both datasets cover the same period of the years 2006-2010.</p>
<div id="7a4555b9" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<pre><code>'Train_ds Sold Houses'</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>'Test_ds Sold Houses'</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>2007    363
2008    318
2009    309
2006    305
2010    164
Name: YrSold, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h2>
<p>I created a copy of train_ds called eda_ds that will be cleaned and used in exploratory data analysis.</p>
<div id="4c30dff4" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MSSubClass</th>
<th data-quarto-table-cell-role="th">MSZoning</th>
<th data-quarto-table-cell-role="th">LotFrontage</th>
<th data-quarto-table-cell-role="th">LotArea</th>
<th data-quarto-table-cell-role="th">Street</th>
<th data-quarto-table-cell-role="th">Alley</th>
<th data-quarto-table-cell-role="th">LotShape</th>
<th data-quarto-table-cell-role="th">LandContour</th>
<th data-quarto-table-cell-role="th">Utilities</th>
<th data-quarto-table-cell-role="th">LotConfig</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">PoolArea</th>
<th data-quarto-table-cell-role="th">PoolQC</th>
<th data-quarto-table-cell-role="th">Fence</th>
<th data-quarto-table-cell-role="th">MiscFeature</th>
<th data-quarto-table-cell-role="th">MiscVal</th>
<th data-quarto-table-cell-role="th">MoSold</th>
<th data-quarto-table-cell-role="th">YrSold</th>
<th data-quarto-table-cell-role="th">SaleType</th>
<th data-quarto-table-cell-role="th">SaleCondition</th>
<th data-quarto-table-cell-role="th">SalePrice</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Id</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>60</td>
<td>RL</td>
<td>65.0</td>
<td>8450</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>2</td>
<td>2008</td>
<td>WD</td>
<td>Normal</td>
<td>208500</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2</th>
<td>20</td>
<td>RL</td>
<td>80.0</td>
<td>9600</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>FR2</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>5</td>
<td>2007</td>
<td>WD</td>
<td>Normal</td>
<td>181500</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3</th>
<td>60</td>
<td>RL</td>
<td>68.0</td>
<td>11250</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>Inside</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>9</td>
<td>2008</td>
<td>WD</td>
<td>Normal</td>
<td>223500</td>
</tr>
</tbody>
</table>

<p>3 rows × 80 columns</p>
</div>
</div>
</div>
<p>Checking datatypes in eda_ds:</p>
<div id="44bc1f23" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Integer Variables: ['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']
Float Variables: ['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
Categorical Variables: ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']</code></pre>
</div>
</div>
<p>Some variables were not in the proper data types, for example, the categorical values in numerical data types. For simplicity, I changed float variables to integer variables. I found and imputed missing values.</p>
<p>Missing values:</p>
<div id="ba0b00ab" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtExposure      38
BsmtFinType2      38
BsmtCond          37
BsmtQual          37
BsmtFinType1      37
MasVnrArea         8
MasVnrType         8
Electrical         1
dtype: int64</code></pre>
</div>
</div>
<p>Final check:</p>
<div id="80a025d1" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   object 
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1460 non-null   int64  
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   object 
 17  OverallCond    1460 non-null   object 
 18  YearBuilt      1460 non-null   float64
 19  YearRemodAdd   1460 non-null   float64
 20  RoofStyle      1460 non-null   object 
 21  RoofMatl       1460 non-null   object 
 22  Exterior1st    1460 non-null   object 
 23  Exterior2nd    1460 non-null   object 
 24  MasVnrType     1460 non-null   object 
 25  MasVnrArea     1460 non-null   int64  
 26  ExterQual      1460 non-null   object 
 27  ExterCond      1460 non-null   object 
 28  Foundation     1460 non-null   object 
 29  BsmtQual       1460 non-null   object 
 30  BsmtCond       1460 non-null   object 
 31  BsmtExposure   1460 non-null   object 
 32  BsmtFinType1   1460 non-null   object 
 33  BsmtFinSF1     1460 non-null   int64  
 34  BsmtFinType2   1460 non-null   object 
 35  BsmtFinSF2     1460 non-null   int64  
 36  BsmtUnfSF      1460 non-null   int64  
 37  TotalBsmtSF    1460 non-null   int64  
 38  Heating        1460 non-null   object 
 39  HeatingQC      1460 non-null   object 
 40  CentralAir     1460 non-null   object 
 41  Electrical     1460 non-null   object 
 42  1stFlrSF       1460 non-null   int64  
 43  2ndFlrSF       1460 non-null   int64  
 44  LowQualFinSF   1460 non-null   int64  
 45  GrLivArea      1460 non-null   int64  
 46  BsmtFullBath   1460 non-null   object 
 47  BsmtHalfBath   1460 non-null   object 
 48  FullBath       1460 non-null   object 
 49  HalfBath       1460 non-null   object 
 50  BedroomAbvGr   1460 non-null   object 
 51  KitchenAbvGr   1460 non-null   object 
 52  KitchenQual    1460 non-null   object 
 53  TotRmsAbvGrd   1460 non-null   object 
 54  Functional     1460 non-null   object 
 55  Fireplaces     1460 non-null   object 
 56  FireplaceQu    1460 non-null   object 
 57  GarageType     1460 non-null   object 
 58  GarageYrBlt    1460 non-null   int64  
 59  GarageFinish   1460 non-null   object 
 60  GarageCars     1460 non-null   object 
 61  GarageArea     1460 non-null   int64  
 62  GarageQual     1460 non-null   object 
 63  GarageCond     1460 non-null   object 
 64  PavedDrive     1460 non-null   object 
 65  WoodDeckSF     1460 non-null   int64  
 66  OpenPorchSF    1460 non-null   int64  
 67  EnclosedPorch  1460 non-null   int64  
 68  3SsnPorch      1460 non-null   int64  
 69  ScreenPorch    1460 non-null   int64  
 70  PoolArea       1460 non-null   int64  
 71  PoolQC         1460 non-null   object 
 72  Fence          1460 non-null   object 
 73  MiscFeature    1460 non-null   object 
 74  MiscVal        1460 non-null   int64  
 75  MoSold         1460 non-null   object 
 76  YrSold         1460 non-null   int64  
 77  SaleType       1460 non-null   object 
 78  SaleCondition  1460 non-null   object 
 79  SalePrice      1460 non-null   int64  
dtypes: float64(2), int64(22), object(56)
memory usage: 923.9+ KB</code></pre>
</div>
</div>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">EDA</h2>
<p>Exploratory Data Analysis (EDA) is conducted to gain insight into the distributions and characteristics of the dataset prior to modeling. Visualization techniques play a key role in identifying skewness, sparsity, outliers, and potential data quality issues.</p>
<p>For this purpose, histograms are used to analyze numerical variables, and bar plots are used to examine categorical variables.</p>
<p>The following histograms summarize the distributions of the numerical features and highlight key patterns relevant for feature engineering and model selection.</p>
<section id="histograms" class="level3">
<h3 class="anchored" data-anchor-id="histograms">Histograms</h3>
<div id="d227cf45" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="barplots" class="level3">
<h3 class="anchored" data-anchor-id="barplots">Barplots</h3>
<div id="661c8e01" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="average-sale-price-and-total-amount-of-sales-for-every-year" class="level3">
<h3 class="anchored" data-anchor-id="average-sale-price-and-total-amount-of-sales-for-every-year">Average Sale Price and Total Amount of Sales for Every Year</h3>
<div id="491896a9" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="5b203f5b" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Average prices increased from 2006 to a peak in 2007, followed by a sharp decline in 2008. A partial recovery is observed in 2009, with prices decreasing again in 2010.<br>
</p>
<p>The total number of sales increases from 2006 to 2007, declines in 2008, and then reaches its highest level in 2009. A substantial drop in the number of sales is observed in 2010.<br>
</p>
<p>This noticeable volatility is timed closely with the global economic crisis of 2008.</p>
</section>
<section id="correlation-of-variables-with-saleprice" class="level3">
<h3 class="anchored" data-anchor-id="correlation-of-variables-with-saleprice">Correlation of Variables with SalePrice</h3>
<p>To explore the relationship between numerical features and the target variable SalePrice, scatterplots are used to visualize potential correlations. These plots allow the identification of linear or nonlinear trends between each numerical predictor and the sale price.<br>
Positive or negative correlations may. be observed as diagonally. increasing or decreasing patterns in the scatter plots, while weak or no correlation is indicated by a more diffuse or random distribution of points.</p>
<p>Scatterplots:</p>
<div id="d0c3109c" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Variables ‘LotFrontage’, ‘BSmtFinSF1’, ‘TotalBsmtSF’, ‘1stFlrSF’, ‘2ndFlrSF’, ‘GrLivArea’, ‘GarageArea’ seem to have considerable correlation.</p>
<p>I am going to use median house prices in correlation with ‘year’ variables - ‘YearBuilt’, ‘YearRemodAdd’, ‘GarageYrBlt’ to reduce the influence of extreme values and outliers.</p>
<p>Median sales for ‘year’ variables:</p>
<div id="84ff1f79" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="49bf3d79" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="d27c638e" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>All ‘year’ variables showed a good correlation with SalePrice.</p>
<p>I used box plots to examine the relationship between categorical variables and the target variable ‘SalePrice’. Boxplots provide a concise summary of the distribution of sale prices within each category, allowing for comparison of medians, variability, and the presence of outliers across groups.</p>
<p>Boxplots:</p>
<div id="4b1a4297" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-21-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-21-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="house_price_prediction_files/figure-html/cell-21-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The box plots indicated that variables related to material quality, overall condition, number of rooms, number of fireplaces, and garage capacity are strongly associated with ‘SalePrice’.</p>
</section>
</section>
<section id="feature-selection" class="level2">
<h2 class="anchored" data-anchor-id="feature-selection">Feature Selection</h2>
<p>Features chosen by analysis of supposed low correlation in plots: ‘Alley’, ‘LotShape’, ‘LandContour’, ‘Utilities’, ‘LotConfig’, ‘LandSlope’, ‘Condition2’, ‘BldgType’, ‘HouseStyle’, ‘RoofStyle’, ‘BedroomAbvGr’, ‘KitchenAbvGr’, ‘BsmtFinType2’, ‘BsmtFinSF2’, ‘BsmtUnfSF’, ‘LowQualFinSF’, ‘Exterior1st’, ‘Exterior2nd’, ‘BsmtFullBath’, ‘BsmtHalfBath’,‘Electrical’, ‘Functional’, ‘WoodDeckSF’, ‘OpenPorchSF’, ‘EnclosedPorch’, ‘3SsnPorch’, ‘ScreenPorch’, ‘PoolArea’, ‘PoolQC’, ‘Fence’, ‘MiscVal’, ‘MoSold’. These features were tested by the model to prove their ability to lower the correction of the prediction model.</p>
<p>Feature selection:</p>
<div id="9617c8a3" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>['Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'Functional',
 'Exterior1st',
 'Exterior2nd',
 'Fence',
 'MiscVal',
 'MiscFeature',
 'MoSold']</code></pre>
</div>
</div>
<section id="why-these-features-increase-or-decrease-model-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="why-these-features-increase-or-decrease-model-accuracy">Why these features increase or decrease model accuracy?</h3>
<p>Feature selection was performed iteratively, removing low-signal variables and validating each change using cross-validation. Features were retained only if their removal improved or maintained generalization performance. Features such as ‘Alley’, ‘Fence’, ‘MiscFeature’, and ‘MiscVal’ contain a high proportion of missing values, were found to be weak predictors. Similarly, features including ‘LotShape’, ‘LandContour’, ‘LotConfig’, ‘LandSlope’, and ‘Condition2’ seem to be rather irrelevant for prediction. Several structurally relevant variables, such as ‘BldgType’, ‘HouseStyle’, ‘BedroomAbvGr’, ‘KitchenAbvGr’, ‘Utilities’, ‘Functional’, ‘Exterior1st’, and ‘Exterior2nd’, also demonstrate limited contribution. Their predictive effect appears to be largely captured by stronger correlated variables such as ‘GrLivArea’, ‘TotRmsAbvGrd’, and ‘OverallQual’. ‘MoSold’ shows only a weak seasonal influence on pricing. In contrast, variables (‘BsmtFinType2’, ‘BsmtFinSF2’, ‘BsmtUnfSF’, ‘LowQualFinSF’, ‘BsmtFullBath’, ‘BsmtHalfBath’) provide meaningful information about usable living space and structural value. Outdoor and amenity features (‘WoodDeckSF’, ‘OpenPorchSF’, ‘EnclosedPorch’, ‘3SsnPorch’, ‘ScreenPorch’, ‘PoolArea’, ‘PoolQC’), although sparse, are associated with higher-end properties and contributed positively to predictive performance.</p>
</section>
</section>
<section id="ridge-model" class="level2">
<h2 class="anchored" data-anchor-id="ridge-model">Ridge Model</h2>
<p>I implemented a Ridge regression model using a fully pipeline-based preprocessing workflow, including log transformation of the target, imputation, scaling, one-hot encoding, skew correction, and custom feature engineering.<br>
Ridge regression is the regular linear regression with a built-in “brake pedal.” When a model tries too hard to perfectly fit the training data, it can give some features very large weights. That often leads to overfitting — great performance on training data, worse performance on new data.<br>
Ridge adds a penalty for large weights. It gently pushes all coefficients to be smaller, making the model more stable and less sensitive to noise.</p>
<p>I searched for the best value of alpha (the strength of regularization) using 5-fold cross-validation.<br>
The data was split into 5 parts, and the model was trained and validated five times, each time using a different fold as validation. I tested 40 different alpha values ranging from 0.001 to 100, spaced logarithmically to explore both very small and large regularization strengths.<br>
The model was evaluated using RMSE, and the alpha that produced the lowest average RMSE across folds was selected.</p>
<p>Values:</p>
<div id="2852a8cd" class="cell" data-execution_count="24">
<div class="cell-output cell-output-stdout">
<pre><code>Best alpha: 0.001
Best CV RMSE: 0.12746354709463686</code></pre>
</div>
</div>
<p>Fitting model:</p>
<div id="0fa252d6" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display" data-execution_count="25">
<style>#sk-container-id-1 {color: black;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>Pipeline(steps=[('fe', FeatureEngineer()),
                ('skew',
                 SkewLog1p(exclude=('YearBuilt', 'YearRemodAdd', 'GarageYrBlt',
                                    'YrSold', 'MoSold'))),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F001F8D50&gt;),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F77B37050&gt;)])),
                ('regressor', Ridge(alpha=0.001))])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox"><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">Pipeline</label><div class="sk-toggleable__content"><pre>Pipeline(steps=[('fe', FeatureEngineer()),
                ('skew',
                 SkewLog1p(exclude=('YearBuilt', 'YearRemodAdd', 'GarageYrBlt',
                                    'YrSold', 'MoSold'))),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F001F8D50&gt;),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F77B37050&gt;)])),
                ('regressor', Ridge(alpha=0.001))])</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox"><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">FeatureEngineer</label><div class="sk-toggleable__content"><pre>FeatureEngineer()</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-3" type="checkbox"><label for="sk-estimator-id-3" class="sk-toggleable__label sk-toggleable__label-arrow">SkewLog1p</label><div class="sk-toggleable__content"><pre>SkewLog1p(exclude=('YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'YrSold',
                   'MoSold'))</pre></div></div></div><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-4" type="checkbox"><label for="sk-estimator-id-4" class="sk-toggleable__label sk-toggleable__label-arrow">preprocessor: ColumnTransformer</label><div class="sk-toggleable__content"><pre>ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F001F8D50&gt;),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 &lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F77B37050&gt;)])</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-5" type="checkbox"><label for="sk-estimator-id-5" class="sk-toggleable__label sk-toggleable__label-arrow">num</label><div class="sk-toggleable__content"><pre>&lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F001F8D50&gt;</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-6" type="checkbox"><label for="sk-estimator-id-6" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='median')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-7" type="checkbox"><label for="sk-estimator-id-7" class="sk-toggleable__label sk-toggleable__label-arrow">StandardScaler</label><div class="sk-toggleable__content"><pre>StandardScaler()</pre></div></div></div></div></div></div></div></div><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-8" type="checkbox"><label for="sk-estimator-id-8" class="sk-toggleable__label sk-toggleable__label-arrow">cat</label><div class="sk-toggleable__content"><pre>&lt;sklearn.compose._column_transformer.make_column_selector object at 0x0000027F77B37050&gt;</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-9" type="checkbox"><label for="sk-estimator-id-9" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='most_frequent')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-10" type="checkbox"><label for="sk-estimator-id-10" class="sk-toggleable__label sk-toggleable__label-arrow">OneHotEncoder</label><div class="sk-toggleable__content"><pre>OneHotEncoder(handle_unknown='ignore')</pre></div></div></div></div></div></div></div></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-11" type="checkbox"><label for="sk-estimator-id-11" class="sk-toggleable__label sk-toggleable__label-arrow">Ridge</label><div class="sk-toggleable__content"><pre>Ridge(alpha=0.001)</pre></div></div></div></div></div></div></div>
</div>
</div>
<p>The model is evaluated on the validation set using RMSE and R² to measure prediction accuracy and explanatory power. RMSE measures the average size of prediction errors. R² measures how much of the target variance the model explains.</p>
<p>https://en.wikipedia.org/wiki/Root_mean_square_deviation https://en.wikipedia.org/wiki/Coefficient_of_determination</p>
<p>RMSE and R²:</p>
<div id="43a641db" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>Validation RMSE (log scale): 0.117803
Validation R²: 0.925634</code></pre>
</div>
</div>
<p>RMSE ≈ 0.118<br>
R² ≈ 0.925</p>
<p>This means: 1. Errors are relatively small 2. The model explains most price variation 3. Strong linear baseline performance</p>
<p>I converted predictions back to real prices and calculated RMSE in dollars:</p>
<p>Final prediction for test_ds:</p>
<div id="e5e43f69" class="cell" data-execution_count="28">
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>array([125422.5262022 , 157256.02449643, 185985.52322632, 201042.53838441,
       204879.86873829, 174075.29267014, 184222.20882944, 162441.07234119,
       196948.19904027, 118657.72182559])</code></pre>
</div>
</div>
<p>Saving prediction into test.csv:</p>
<div id="5910a0d3" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Id</th>
<th data-quarto-table-cell-role="th">MSSubClass</th>
<th data-quarto-table-cell-role="th">MSZoning</th>
<th data-quarto-table-cell-role="th">LotFrontage</th>
<th data-quarto-table-cell-role="th">LotArea</th>
<th data-quarto-table-cell-role="th">Street</th>
<th data-quarto-table-cell-role="th">Alley</th>
<th data-quarto-table-cell-role="th">LotShape</th>
<th data-quarto-table-cell-role="th">LandContour</th>
<th data-quarto-table-cell-role="th">Utilities</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">PoolArea</th>
<th data-quarto-table-cell-role="th">PoolQC</th>
<th data-quarto-table-cell-role="th">Fence</th>
<th data-quarto-table-cell-role="th">MiscFeature</th>
<th data-quarto-table-cell-role="th">MiscVal</th>
<th data-quarto-table-cell-role="th">MoSold</th>
<th data-quarto-table-cell-role="th">YrSold</th>
<th data-quarto-table-cell-role="th">SaleType</th>
<th data-quarto-table-cell-role="th">SaleCondition</th>
<th data-quarto-table-cell-role="th">SalePrice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1461</td>
<td>20</td>
<td>RH</td>
<td>80.0</td>
<td>11622</td>
<td>Pave</td>
<td>NaN</td>
<td>Reg</td>
<td>Lvl</td>
<td>AllPub</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>MnPrv</td>
<td>NaN</td>
<td>0</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>125422.526202</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1462</td>
<td>20</td>
<td>RL</td>
<td>81.0</td>
<td>14267</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>Gar2</td>
<td>12500</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>157256.024496</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1463</td>
<td>60</td>
<td>RL</td>
<td>74.0</td>
<td>13830</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>MnPrv</td>
<td>NaN</td>
<td>0</td>
<td>3</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>185985.523226</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1464</td>
<td>60</td>
<td>RL</td>
<td>78.0</td>
<td>9978</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>Lvl</td>
<td>AllPub</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>6</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>201042.538384</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1465</td>
<td>120</td>
<td>RL</td>
<td>43.0</td>
<td>5005</td>
<td>Pave</td>
<td>NaN</td>
<td>IR1</td>
<td>HLS</td>
<td>AllPub</td>
<td>...</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0</td>
<td>1</td>
<td>2010</td>
<td>WD</td>
<td>Normal</td>
<td>204879.868738</td>
</tr>
</tbody>
</table>

<p>5 rows × 81 columns</p>
</div>
</div>
</div>
<p>Cross validation results:</p>
<div id="8b1efcc9" class="cell" data-execution_count="30">
<div class="cell-output cell-output-stdout">
<pre><code>CV RMSE: 0.1256359042076371
Std: 0.013017391589482114</code></pre>
</div>
</div>
</section>
<section id="final-project-summary" class="level2">
<h2 class="anchored" data-anchor-id="final-project-summary">Final Project Summary:</h2>
<p>The goal of this project was to predict house sale prices of the Ames Housing dataset, applying preprocessing, EDA, feature pruning, feature engineering, regularization, and cross-validation to build a stable and interpretable regression model.</p>
<p>Model Performance:</p>
<p>CV RMSE (log scale): 0.1256</p>
<p>Standard deviation: 0.0130</p>
<p>This indicates:<br>
* Strong predictive accuracy for a linear model<br>
* Stable performance across folds<br>
* Good bias–variance balance<br>
* No evidence of overfitting</p>
<p>The model performs near the expected ceiling for regularized linear regression on this dataset.</p>
<p>Conclusion:</p>
<p>Ridge regression benefits from controlled feature pruning. While weak categorical variables can increase noise after encoding, regularization stabilizes coefficient estimates in the presence of multicollinearity. The final Ridge model provides a robust, interpretable, and well-validated baseline for house price prediction. It demonstrates strong generalization performance and sound modeling practices.</p>
<hr>
</section>
</section>
<section id="end" class="level1">
<h1>End</h1>
<hr>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<p>MSSubClass: Identifies the type of dwelling involved in the sale.</p>
<pre><code>    20  1-STORY 1946 &amp; NEWER ALL STYLES
    30  1-STORY 1945 &amp; OLDER
    40  1-STORY W/FINISHED ATTIC ALL AGES
    45  1-1/2 STORY - UNFINISHED ALL AGES
    50  1-1/2 STORY FINISHED ALL AGES
    60  2-STORY 1946 &amp; NEWER
    70  2-STORY 1945 &amp; OLDER
    75  2-1/2 STORY ALL AGES
    80  SPLIT OR MULTI-LEVEL
    85  SPLIT FOYER
    90  DUPLEX - ALL STYLES AND AGES
   120  1-STORY PUD (Planned Unit Development) - 1946 &amp; NEWER
   150  1-1/2 STORY PUD - ALL AGES
   160  2-STORY PUD - 1946 &amp; NEWER
   180  PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
   190  2 FAMILY CONVERSION - ALL STYLES AND AGES</code></pre>
<p>MSZoning: Identifies the general zoning classification of the sale.</p>
<pre><code>   A    Agriculture
   C    Commercial
   FV   Floating Village Residential
   I    Industrial
   RH   Residential High Density
   RL   Residential Low Density
   RP   Residential Low Density Park 
   RM   Residential Medium Density</code></pre>
<p>LotFrontage: Linear feet of street connected to property</p>
<p>LotArea: Lot size in square feet</p>
<p>Street: Type of road access to property</p>
<pre><code>   Grvl Gravel  
   Pave Paved
    </code></pre>
<p>Alley: Type of alley access to property</p>
<pre><code>   Grvl Gravel
   Pave Paved
   NA   No alley access
    </code></pre>
<p>LotShape: General shape of property</p>
<pre><code>   Reg  Regular 
   IR1  Slightly irregular
   IR2  Moderately Irregular
   IR3  Irregular
   </code></pre>
<p>LandContour: Flatness of the property</p>
<pre><code>   Lvl  Near Flat/Level 
   Bnk  Banked - Quick and significant rise from street grade to building
   HLS  Hillside - Significant slope from side to side
   Low  Depression
    </code></pre>
<p>Utilities: Type of utilities available</p>
<pre><code>   AllPub   All public Utilities (E,G,W,&amp; S)    
   NoSewr   Electricity, Gas, and Water (Septic Tank)
   NoSeWa   Electricity and Gas Only
   ELO  Electricity only    </code></pre>
<p>LotConfig: Lot configuration</p>
<pre><code>   Inside   Inside lot
   Corner   Corner lot
   CulDSac  Cul-de-sac
   FR2  Frontage on 2 sides of property
   FR3  Frontage on 3 sides of property</code></pre>
<p>LandSlope: Slope of property</p>
<pre><code>   Gtl  Gentle slope
   Mod  Moderate Slope  
   Sev  Severe Slope</code></pre>
<p>Neighborhood: Physical locations within Ames city limits</p>
<pre><code>   Blmngtn  Bloomington Heights
   Blueste  Bluestem
   BrDale   Briardale
   BrkSide  Brookside
   ClearCr  Clear Creek
   CollgCr  College Creek
   Crawfor  Crawford
   Edwards  Edwards
   Gilbert  Gilbert
   IDOTRR   Iowa DOT and Rail Road
   MeadowV  Meadow Village
   Mitchel  Mitchell
   Names    North Ames
   NoRidge  Northridge
   NPkVill  Northpark Villa
   NridgHt  Northridge Heights
   NWAmes   Northwest Ames
   OldTown  Old Town
   SWISU    South &amp; West of Iowa State University
   Sawyer   Sawyer
   SawyerW  Sawyer West
   Somerst  Somerset
   StoneBr  Stone Brook
   Timber   Timberland
   Veenker  Veenker
        </code></pre>
<p>Condition1: Proximity to various conditions</p>
<pre><code>   Artery   Adjacent to arterial street
   Feedr    Adjacent to feeder street   
   Norm Normal  
   RRNn Within 200' of North-South Railroad
   RRAn Adjacent to North-South Railroad
   PosN Near positive off-site feature--park, greenbelt, etc.
   PosA Adjacent to postive off-site feature
   RRNe Within 200' of East-West Railroad
   RRAe Adjacent to East-West Railroad</code></pre>
<p>Condition2: Proximity to various conditions (if more than one is present)</p>
<pre><code>   Artery   Adjacent to arterial street
   Feedr    Adjacent to feeder street   
   Norm Normal  
   RRNn Within 200' of North-South Railroad
   RRAn Adjacent to North-South Railroad
   PosN Near positive off-site feature--park, greenbelt, etc.
   PosA Adjacent to postive off-site feature
   RRNe Within 200' of East-West Railroad
   RRAe Adjacent to East-West Railroad</code></pre>
<p>BldgType: Type of dwelling</p>
<pre><code>   1Fam Single-family Detached  
   2FmCon   Two-family Conversion; originally built as one-family dwelling
   Duplx    Duplex
   TwnhsE   Townhouse End Unit
   TwnhsI   Townhouse Inside Unit</code></pre>
<p>HouseStyle: Style of dwelling</p>
<pre><code>   1Story   One story
   1.5Fin   One and one-half story: 2nd level finished
   1.5Unf   One and one-half story: 2nd level unfinished
   2Story   Two story
   2.5Fin   Two and one-half story: 2nd level finished
   2.5Unf   Two and one-half story: 2nd level unfinished
   SFoyer   Split Foyer
   SLvl Split Level</code></pre>
<p>OverallQual: Rates the overall material and finish of the house</p>
<pre><code>   10   Very Excellent
   9    Excellent
   8    Very Good
   7    Good
   6    Above Average
   5    Average
   4    Below Average
   3    Fair
   2    Poor
   1    Very Poor</code></pre>
<p>OverallCond: Rates the overall condition of the house</p>
<pre><code>   10   Very Excellent
   9    Excellent
   8    Very Good
   7    Good
   6    Above Average   
   5    Average
   4    Below Average   
   3    Fair
   2    Poor
   1    Very Poor
    </code></pre>
<p>YearBuilt: Original construction date</p>
<p>YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)</p>
<p>RoofStyle: Type of roof</p>
<pre><code>   Flat Flat
   Gable    Gable
   Gambrel  Gabrel (Barn)
   Hip  Hip
   Mansard  Mansard
   Shed Shed
    </code></pre>
<p>RoofMatl: Roof material</p>
<pre><code>   ClyTile  Clay or Tile
   CompShg  Standard (Composite) Shingle
   Membran  Membrane
   Metal    Metal
   Roll Roll
   Tar&amp;Grv  Gravel &amp; Tar
   WdShake  Wood Shakes
   WdShngl  Wood Shingles
    </code></pre>
<p>Exterior1st: Exterior covering on house</p>
<pre><code>   AsbShng  Asbestos Shingles
   AsphShn  Asphalt Shingles
   BrkComm  Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   CemntBd  Cement Board
   HdBoard  Hard Board
   ImStucc  Imitation Stucco
   MetalSd  Metal Siding
   Other    Other
   Plywood  Plywood
   PreCast  PreCast 
   Stone    Stone
   Stucco   Stucco
   VinylSd  Vinyl Siding
   Wd Sdng  Wood Siding
   WdShing  Wood Shingles</code></pre>
<p>Exterior2nd: Exterior covering on house (if more than one material)</p>
<pre><code>   AsbShng  Asbestos Shingles
   AsphShn  Asphalt Shingles
   BrkComm  Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   CemntBd  Cement Board
   HdBoard  Hard Board
   ImStucc  Imitation Stucco
   MetalSd  Metal Siding
   Other    Other
   Plywood  Plywood
   PreCast  PreCast
   Stone    Stone
   Stucco   Stucco
   VinylSd  Vinyl Siding
   Wd Sdng  Wood Siding
   WdShing  Wood Shingles</code></pre>
<p>MasVnrType: Masonry veneer type</p>
<pre><code>   BrkCmn   Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   None None
   Stone    Stone</code></pre>
<p>MasVnrArea: Masonry veneer area in square feet</p>
<p>ExterQual: Evaluates the quality of the material on the exterior</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
    </code></pre>
<p>ExterCond: Evaluates the present condition of the material on the exterior</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
    </code></pre>
<p>Foundation: Type of foundation</p>
<pre><code>   BrkTil   Brick &amp; Tile
   CBlock   Cinder Block
   PConc    Poured Contrete 
   Slab Slab
   Stone    Stone
   Wood Wood
    </code></pre>
<p>BsmtQual: Evaluates the height of the basement</p>
<pre><code>   Ex   Excellent (100+ inches) 
   Gd   Good (90-99 inches)
   TA   Typical (80-89 inches)
   Fa   Fair (70-79 inches)
   Po   Poor (&lt;70 inches
   NA   No Basement
    </code></pre>
<p>BsmtCond: Evaluates the general condition of the basement</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Typical - slight dampness allowed
   Fa   Fair - dampness or some cracking or settling
   Po   Poor - Severe cracking, settling, or wetness
   NA   No Basement</code></pre>
<p>BsmtExposure: Refers to walkout or garden level walls</p>
<pre><code>   Gd   Good Exposure
   Av   Average Exposure (split levels or foyers typically score average or above)  
   Mn   Mimimum Exposure
   No   No Exposure
   NA   No Basement</code></pre>
<p>BsmtFinType1: Rating of basement finished area</p>
<pre><code>   GLQ  Good Living Quarters
   ALQ  Average Living Quarters
   BLQ  Below Average Living Quarters   
   Rec  Average Rec Room
   LwQ  Low Quality
   Unf  Unfinshed
   NA   No Basement
    </code></pre>
<p>BsmtFinSF1: Type 1 finished square feet</p>
<p>BsmtFinType2: Rating of basement finished area (if multiple types)</p>
<pre><code>   GLQ  Good Living Quarters
   ALQ  Average Living Quarters
   BLQ  Below Average Living Quarters   
   Rec  Average Rec Room
   LwQ  Low Quality
   Unf  Unfinshed
   NA   No Basement</code></pre>
<p>BsmtFinSF2: Type 2 finished square feet</p>
<p>BsmtUnfSF: Unfinished square feet of basement area</p>
<p>TotalBsmtSF: Total square feet of basement area</p>
<p>Heating: Type of heating</p>
<pre><code>   Floor    Floor Furnace
   GasA Gas forced warm air furnace
   GasW Gas hot water or steam heat
   Grav Gravity furnace 
   OthW Hot water or steam heat other than gas
   Wall Wall furnace
    </code></pre>
<p>HeatingQC: Heating quality and condition</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
    </code></pre>
<p>CentralAir: Central air conditioning</p>
<pre><code>   N    No
   Y    Yes
    </code></pre>
<p>Electrical: Electrical system</p>
<pre><code>   SBrkr    Standard Circuit Breakers &amp; Romex
   FuseA    Fuse Box over 60 AMP and all Romex wiring (Average) 
   FuseF    60 AMP Fuse Box and mostly Romex wiring (Fair)
   FuseP    60 AMP Fuse Box and mostly knob &amp; tube wiring (poor)
   Mix  Mixed
    </code></pre>
<p>1stFlrSF: First Floor square feet</p>
<p>2ndFlrSF: Second floor square feet</p>
<p>LowQualFinSF: Low quality finished square feet (all floors)</p>
<p>GrLivArea: Above grade (ground) living area square feet</p>
<p>BsmtFullBath: Basement full bathrooms</p>
<p>BsmtHalfBath: Basement half bathrooms</p>
<p>FullBath: Full bathrooms above grade</p>
<p>HalfBath: Half baths above grade</p>
<p>Bedroom: Bedrooms above grade (does NOT include basement bedrooms)</p>
<p>Kitchen: Kitchens above grade</p>
<p>KitchenQual: Kitchen quality</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
    </code></pre>
<p>TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)</p>
<p>Functional: Home functionality (Assume typical unless deductions are warranted)</p>
<pre><code>   Typ  Typical Functionality
   Min1 Minor Deductions 1
   Min2 Minor Deductions 2
   Mod  Moderate Deductions
   Maj1 Major Deductions 1
   Maj2 Major Deductions 2
   Sev  Severely Damaged
   Sal  Salvage only
    </code></pre>
<p>Fireplaces: Number of fireplaces</p>
<p>FireplaceQu: Fireplace quality</p>
<pre><code>   Ex   Excellent - Exceptional Masonry Fireplace
   Gd   Good - Masonry Fireplace in main level
   TA   Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
   Fa   Fair - Prefabricated Fireplace in basement
   Po   Poor - Ben Franklin Stove
   NA   No Fireplace
    </code></pre>
<p>GarageType: Garage location</p>
<pre><code>   2Types   More than one type of garage
   Attchd   Attached to home
   Basment  Basement Garage
   BuiltIn  Built-In (Garage part of house - typically has room above garage)
   CarPort  Car Port
   Detchd   Detached from home
   NA   No Garage
    </code></pre>
<p>GarageYrBlt: Year garage was built</p>
<p>GarageFinish: Interior finish of the garage</p>
<pre><code>   Fin  Finished
   RFn  Rough Finished  
   Unf  Unfinished
   NA   No Garage
    </code></pre>
<p>GarageCars: Size of garage in car capacity</p>
<p>GarageArea: Size of garage in square feet</p>
<p>GarageQual: Garage quality</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
   NA   No Garage
    </code></pre>
<p>GarageCond: Garage condition</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
   NA   No Garage
    </code></pre>
<p>PavedDrive: Paved driveway</p>
<pre><code>   Y    Paved 
   P    Partial Pavement
   N    Dirt/Gravel
    </code></pre>
<p>WoodDeckSF: Wood deck area in square feet</p>
<p>OpenPorchSF: Open porch area in square feet</p>
<p>EnclosedPorch: Enclosed porch area in square feet</p>
<p>3SsnPorch: Three season porch area in square feet</p>
<p>ScreenPorch: Screen porch area in square feet</p>
<p>PoolArea: Pool area in square feet</p>
<p>PoolQC: Pool quality</p>
<pre><code>   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   NA   No Pool
    </code></pre>
<p>Fence: Fence quality</p>
<pre><code>   GdPrv    Good Privacy
   MnPrv    Minimum Privacy
   GdWo Good Wood
   MnWw Minimum Wood/Wire
   NA   No Fence</code></pre>
<p>MiscFeature: Miscellaneous feature not covered in other categories</p>
<pre><code>   Elev Elevator
   Gar2 2nd Garage (if not described in garage section)
   Othr Other
   Shed Shed (over 100 SF)
   TenC Tennis Court
   NA   None
    </code></pre>
<p>MiscVal: $Value of miscellaneous feature</p>
<p>MoSold: Month Sold (MM)</p>
<p>YrSold: Year Sold (YYYY)</p>
<p>SaleType: Type of sale</p>
<pre><code>   WD   Warranty Deed - Conventional
   CWD  Warranty Deed - Cash
   VWD  Warranty Deed - VA Loan
   New  Home just constructed and sold
   COD  Court Officer Deed/Estate
   Con  Contract 15% Down payment regular terms
   ConLw    Contract Low Down payment and low interest
   ConLI    Contract Low Interest
   ConLD    Contract Low Down
   Oth  Other
    </code></pre>
<p>SaleCondition: Condition of sale</p>
<pre><code>   Normal   Normal Sale
   Abnorml  Abnormal Sale -  trade, foreclosure, short sale
   AdjLand  Adjoining Land Purchase
   Alloca   Allocation - two linked properties with separate deeds, typically condo with a garage unit  
   Family   Sale between family members
   Partial  Home was not completed when last assessed (associated with New Homes)</code></pre>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>